'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { formatCurrency } from '@/lib/utils/currency'

export type CatalogCourse = { slug: string; title: string; subtitle: string | null; description: string; kind: string; category: string; level: string; priceKes: number; thumbnailUrl: string | null; lessonCount: number; durationMinutes: number }
export function CourseCatalog({ courses, kind }: { courses: CatalogCourse[]; kind: 'course' | 'masterclass' }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all')
  const categories = Array.from(new Set(courses.map((c) => c.category))).sort()
  const shown = useMemo(() => courses.filter((course) => (category === 'all' || course.category === category) && `${course.title} ${course.subtitle ?? ''} ${course.description} ${course.category}`.toLowerCase().includes(query.toLowerCase().trim())), [courses, category, query])
  const base = kind === 'course' ? '/academy/courses' : '/academy/masterclasses'
  return <div><div className="grid gap-3 border-b border-navy-100 pb-8 sm:grid-cols-[1fr_16rem]"><label><span className="sr-only">Search programs</span><input type="search" placeholder={`Search ${kind === 'course' ? 'courses' : 'masterclasses'} by topic or outcome`} value={query} onChange={(e) => setQuery(e.target.value)} className="min-h-12 w-full rounded-full border border-navy-200 bg-white px-5 text-navy outline-none focus:border-gold focus:ring-2 focus:ring-gold/20" /></label><select aria-label="Filter by category" value={category} onChange={(e) => setCategory(e.target.value)} className="min-h-12 rounded-full border border-navy-200 bg-white px-5 text-navy"><option value="all">All categories</option>{categories.map((c) => <option key={c}>{c}</option>)}</select></div>
    <p className="mt-5 text-sm text-navy-400" aria-live="polite">{shown.length} {shown.length === 1 ? 'program' : 'programs'} found</p>
    {shown.length === 0 ? <div className="mt-8 border border-dashed border-navy-200 bg-white p-10 text-center"><h2 className="font-heading text-xl font-bold text-navy">No matching programs</h2><p className="mt-2 text-navy-500">Try a broader topic or choose all categories.</p></div> : <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{shown.map((course) => <Link key={course.slug} href={`${base}/${course.slug}`} className="group overflow-hidden rounded-2xl border border-navy-100 bg-white shadow-sm transition hover:-translate-y-1 hover:border-gold-300 hover:shadow-lg"><div className="aspect-[16/9] bg-navy p-6 text-white" style={course.thumbnailUrl ? { backgroundImage: `linear-gradient(90deg,rgba(7,22,39,.75),rgba(7,22,39,.25)),url(${course.thumbnailUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined}><span className="rounded-full bg-gold px-3 py-1 text-xs font-bold uppercase text-navy">{course.category}</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wide text-gold-700">{course.level.replace('-', ' ')}</p><h2 className="mt-2 font-heading text-2xl font-bold text-navy group-hover:text-gold-700">{course.title}</h2>{course.subtitle && <p className="mt-2 font-semibold text-navy-500">{course.subtitle}</p>}<p className="mt-4 line-clamp-3 text-sm leading-6 text-navy-500">{course.description}</p><div className="mt-5 flex items-center justify-between border-t border-navy-100 pt-4 text-sm"><span className="text-navy-400">{course.lessonCount} lessons · {course.durationMinutes ? `${course.durationMinutes} min` : 'Self-paced'}</span><strong className="text-navy">{course.priceKes === 0 ? 'Free' : formatCurrency(course.priceKes)}</strong></div></div></Link>)}</div>}
  </div>
}
