import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { db } from '@/lib/db'
import { CourseEnrollCard } from '@/components/courses/CourseEnrollCard'

export async function CourseSalesPage({ slug, kind }: { slug: string; kind: 'course' | 'masterclass' }) {
  const course = await db.course.findFirst({ where: { slug, kind, status: 'published' }, include: { sections: { include: { lessons: { where: { status: 'published' }, orderBy: { position: 'asc' } } }, orderBy: { position: 'asc' } } } })
  if (!course) return null
  const session = await getServerSession(authOptions); const userId = (session?.user as { id?: string } | undefined)?.id
  const enrolled = userId ? Boolean(await db.courseEnrollment.findUnique({ where: { courseId_userId: { courseId: course.id, userId } }, select: { id: true } })) : false
  const lessons = course.sections.flatMap((s) => s.lessons); const minutes = Math.round(lessons.reduce((n, l) => n + (l.durationSeconds ?? 0), 0) / 60)
  return <><section className="bg-navy text-white"><div className="mx-auto grid max-w-content gap-10 px-6 py-20 lg:grid-cols-[1fr_23rem] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">{course.category} · {kind}</p><h1 className="mt-4 max-w-4xl font-heading text-4xl font-bold sm:text-6xl">{course.title}</h1>{course.subtitle && <p className="mt-5 text-xl text-white/80">{course.subtitle}</p>}<p className="mt-6 max-w-3xl text-base leading-8 text-white/70">{course.description}</p><p className="mt-6 text-sm font-semibold text-gold-200">{lessons.length} lessons · {minutes ? `${minutes} minutes` : 'Self-paced'} · {course.level.replace('-', ' ')}</p></div><CourseEnrollCard courseId={course.id} slug={course.slug} kind={course.kind} priceKes={course.priceKes} priceUsd={course.priceUsd} signedIn={Boolean(userId)} email={session?.user?.email ?? undefined} enrolled={enrolled} /></div></section><section className="bg-cream"><div className="mx-auto grid max-w-content gap-12 px-6 py-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-700">What you will gain</p><ul className="mt-5 space-y-4">{course.outcomes.map((outcome) => <li key={outcome} className="flex gap-3 text-navy-600"><span className="font-bold text-gold-700">✓</span>{outcome}</li>)}</ul></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-700">Curriculum</p><div className="mt-5 space-y-4">{course.sections.map((section, si) => <section key={section.id} className="overflow-hidden rounded-xl border border-navy-100 bg-white"><div className="border-b border-navy-100 bg-navy-50 px-5 py-4"><p className="text-xs font-bold uppercase text-navy-400">Section {si + 1}</p><h2 className="mt-1 font-heading text-xl font-bold text-navy">{section.title}</h2></div><ol>{section.lessons.map((lesson, li) => <li key={lesson.id} className="flex items-center justify-between gap-4 border-b border-navy-50 px-5 py-4 last:border-0"><span className="text-sm font-semibold text-navy">{li + 1}. {lesson.title}</span><span className="text-xs text-navy-400">{lesson.isPreview ? 'Preview' : lesson.durationSeconds ? `${Math.ceil(lesson.durationSeconds / 60)} min` : 'Lesson'}</span></li>)}</ol></section>)}</div></div></div></section></>
}
