version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ../../.env.local
  cms:
    build: ../../cms
    ports:
      - '1337:1337'
    env_file:
      - ../../cms/.env
