'use client'
import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/Button'

type Lesson = { id: string; title: string; description: string | null; content: string | null; videoUrl: string | null; durationSeconds: number | null; sectionTitle: string }
export function CoursePlayer({ courseId, courseTitle, lessons, initiallyCompleted, initialLessonId }: { courseId: string; courseTitle: string; lessons: Lesson[]; initiallyCompleted: string[]; initialLessonId?: string | null }) {
  const [activeId, setActiveId] = useState(initialLessonId && lessons.some((l) => l.id === initialLessonId) ? initialLessonId : lessons.find((l) => !initiallyCompleted.includes(l.id))?.id ?? lessons[0]?.id)
  const [completed, setCompleted] = useState(new Set(initiallyCompleted)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const active = lessons.find((l) => l.id === activeId) ?? lessons[0]; const index = lessons.findIndex((l) => l.id === active?.id)
  const percent = lessons.length ? Math.round(completed.size / lessons.length * 100) : 0
  const grouped = useMemo(() => Array.from(new Set(lessons.map((l) => l.sectionTitle))).map((title) => ({ title, lessons: lessons.filter((l) => l.sectionTitle === title) })), [lessons])
  async function setComplete(value: boolean) { if (!active) return; setSaving(true); setMessage(''); const res = await fetch(`/api/courses/${courseId}/lessons/${active.id}/progress`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ completed: value, lastPositionSeconds: 0 }) }); const body = await res.json().catch(() => ({})) as { error?: string; courseCompleted?: boolean }; setSaving(false); if (!res.ok) return setMessage(body.error ?? 'Progress could not be saved.'); const next = new Set(completed); value ? next.add(active.id) : next.delete(active.id); setCompleted(next); if (body.courseCompleted) setMessage('Course complete. Well done.'); else if (value && lessons[index + 1]) setActiveId(lessons[index + 1].id) }
  if (!active) return <p>This course has no published lessons yet.</p>
  return <div className="grid min-h-[calc(100vh-8rem)] gap-6 xl:grid-cols-[20rem_1fr]"><aside className="rounded-2xl bg-navy p-5 text-white"><a href="/dashboard/my-learning" className="text-sm text-gold-200 hover:underline">← My Learning</a><h1 className="mt-5 font-heading text-2xl font-bold">{courseTitle}</h1><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-gold transition-all" style={{ width: `${percent}%` }} /></div><p className="mt-2 text-xs text-white/60">{completed.size} of {lessons.length} lessons complete · {percent}%</p><nav className="mt-7 space-y-6">{grouped.map((section) => <div key={section.title}><p className="text-xs font-bold uppercase tracking-[.15em] text-gold-200">{section.title}</p><div className="mt-2 space-y-1">{section.lessons.map((lesson) => <button key={lesson.id} onClick={() => setActiveId(lesson.id)} className={`flex w-full items-start gap-2 rounded-lg px-3 py-2 text-left text-sm ${lesson.id === active.id ? 'bg-white text-navy' : 'text-white/75 hover:bg-white/10'}`}><span>{completed.has(lesson.id) ? '✓' : '○'}</span><span>{lesson.title}</span></button>)}</div></div>)}</nav></aside><main className="rounded-2xl border border-navy-100 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-bold uppercase tracking-[.15em] text-gold-700">{active.sectionTitle} · Lesson {index + 1} of {lessons.length}</p><h2 className="mt-3 font-heading text-3xl font-bold text-navy sm:text-4xl">{active.title}</h2>{active.description && <p className="mt-3 text-lg text-navy-500">{active.description}</p>}{active.videoUrl && <div className="mt-8 aspect-video overflow-hidden rounded-xl bg-black"><iframe src={active.videoUrl} title={active.title} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen className="h-full w-full" /></div>}{active.content && <div className="mt-8 whitespace-pre-wrap text-base leading-8 text-navy-600">{active.content}</div>}<div className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-navy-100 pt-6"><Button type="button" variant="outline" disabled={index <= 0} onClick={() => setActiveId(lessons[index - 1].id)}>Previous</Button><div className="flex gap-3">{completed.has(active.id) && <Button type="button" variant="ghost" disabled={saving} onClick={() => setComplete(false)}>Mark Incomplete</Button>}<Button type="button" disabled={saving} onClick={() => setComplete(true)}>{saving ? 'Saving…' : completed.has(active.id) ? (lessons[index + 1] ? 'Next Lesson' : 'Completed') : (lessons[index + 1] ? 'Complete & Continue' : 'Complete Course')}</Button></div></div>{message && <p role="status" className="mt-4 rounded-lg bg-gold-50 p-4 font-semibold text-navy">{message}</p>}</main></div>
}
